// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/auth-callback": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/documents/:file": {
    params: {
      "file": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/api/auth-callback" | "/healthcheck" | "/chat" | "/api/chat" | "/documents/:file";
  };
  "auth/routes/auth.login.route.tsx": {
    id: "auth/routes/auth.login.route";
    page: "/login";
  };
  "auth/routes/auth.logout.route.tsx": {
    id: "auth/routes/auth.logout.route";
    page: "/logout";
  };
  "auth/routes/auth.callback.route.tsx": {
    id: "auth/routes/auth.callback.route";
    page: "/api/auth-callback";
  };
  "layout/routes/healthcheck.route.tsx": {
    id: "layout/routes/healthcheck.route";
    page: "/healthcheck";
  };
  "layout/root.layout.tsx": {
    id: "layout/root.layout";
    page: "/" | "/chat" | "/api/chat" | "/documents/:file";
  };
  "layout/routes/home.route.tsx": {
    id: "layout/routes/home.route";
    page: "/";
  };
  "chat/routes/chat.route.tsx": {
    id: "chat/routes/chat.route";
    page: "/chat";
  };
  "chat/routes/api.chat.ts": {
    id: "chat/routes/api.chat";
    page: "/api/chat";
  };
  "chat/routes/documents.route.tsx": {
    id: "chat/routes/documents.route";
    page: "/documents/:file";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "auth/routes/auth.login.route": typeof import("./app/auth/routes/auth.login.route.tsx");
  "auth/routes/auth.logout.route": typeof import("./app/auth/routes/auth.logout.route.tsx");
  "auth/routes/auth.callback.route": typeof import("./app/auth/routes/auth.callback.route.tsx");
  "layout/routes/healthcheck.route": typeof import("./app/layout/routes/healthcheck.route.tsx");
  "layout/root.layout": typeof import("./app/layout/root.layout.tsx");
  "layout/routes/home.route": typeof import("./app/layout/routes/home.route.tsx");
  "chat/routes/chat.route": typeof import("./app/chat/routes/chat.route.tsx");
  "chat/routes/api.chat": typeof import("./app/chat/routes/api.chat.ts");
  "chat/routes/documents.route": typeof import("./app/chat/routes/documents.route.tsx");
};